### ISSUE TITLE
Add instructions for compilation

### ISSUE THREAD

**Issue by Vresod** [AVCADO/win16emu#15]
Expected:
Instructions for compilation in README.md
Reality:
No compilation instructions

This would help anyone trying to contribute to the project.

**Comment by AVCADO** [comment]
It is already compiled, meaning that this wouldn't really be necessary.

**Comment by Vresod** [comment]
But what if you make some changes to the code and want to compile it from source so that the changes work?

**Comment by AVCADO** [comment]
You could just _do that_
